name: CI
on:
  push:
    branches: [ "main", "devcontainers-dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-in-devcontainer:
    name: Build (Dev Containers)
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build in the dev container image
        uses: devcontainers/ci@v0.3
        with:
            #TODO: Enable caching in the template repo and GitHub Packages
            #imageName: ghcr.io/testcontainers/testcontainers-native-builder
            #cacheFrom: ghcr.io/testcontainers/testcontainers-native-builder
            push: never
            runCmd: |
              colcon build --cmake-args -DBUILD_TESTING=ON
            env: |
              GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
      # TODO: Add test reporting

